version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

  service1:
    build: ./service_1   # Fix: correct folder name (not service1)
    expose:
      - "8001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]   # /ping endpoint for health check
      interval: 30s
      timeout: 10s
      retries: 5

  service2:
    build: ./service_2   # Fix: correct folder name (not service2)
    expose:
      - "8002"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]   # /ping endpoint for health check
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

